export type CommandCategory = "todos" | "baits" | "ruleta" | "lore" | "ingame" | "sonidos";

export interface CommandItem {
  id: string;
  name: string;
  category: "baits" | "ruleta" | "lore" | "ingame" | "sonidos";
  tag: string;
  shortDesc: string;
  whatItDoes: string;
  whyItExists: string;
  botResponse: string;
  isBait?: boolean;
  soundName?: string;
  botType: "Nightbot" | "StreamElements" | "Dixper / In-Game" | "Sound Alert";
  syntaxExample?: string;
  // Campos Comerciales de Tienda
  isPurchasable?: boolean;
  purchaseUrl?: string;
  priceLabel?: string;
  priceArs?: string;
  priceUsd?: string;
  priceCoins?: string;
  trollLevel?: number; // 1 a 5
  hardwareTarget?: string;
  triggerGuide?: string;
  paymentMethods?: string[];
  purchasePlatform?: string;
}

export interface DixperCrate {
  id: string;
  name: string;
  tier: "bronce" | "plata" | "oro";
  priceUsd: string;
  priceArs: string;
  coins: string;
  skillsCount: string;
  description: string;
  includedSkills: string[];
  purchaseUrl: string;
  badge: string;
  highlight?: boolean;
}

export interface WeezyxPack {
  id: string;
  name: string;
  priceArs: string;
  priceUsd: string;
  description: string;
  characterLimit?: string;
  purchaseUrl: string;
  tag: string;
  badge?: string;
}

export interface TwitchBounty {
  id: string;
  name: string;
  currency: "Bits" | "Puntos";
  costLabel: string;
  approxArs: string;
  description: string;
  commandSyntax: string;
  targetSquad: string;
  purchaseUrl: string;
}

export const DIXPER_CRATES: DixperCrate[] = [
  {
    id: "crate-bronce",
    name: "Caja de Bronce (Starter Troll)",
    tier: "bronce",
    priceUsd: "$1.99 USD",
    priceArs: "~$2.400 ARS",
    coins: "150 Coins",
    skillsCount: "3 Habilidades",
    description: "Ideal para tu primer sabotaje. Trae habilidades para alterar la vista, cambios de mira o ruidos repentinos.",
    includedSkills: ["Susto Leve", "Sensibilidad x2", "Mira Distorsionada", "Audio Sirena"],
    purchaseUrl: "https://dixper.gg/pipa_arg",
    badge: "ECONÓMICA",
  },
  {
    id: "crate-plata",
    name: "Caja de Plata (Troll Pro)",
    tier: "plata",
    priceUsd: "$4.99 USD",
    priceArs: "~$6.000 ARS",
    coins: "400 Coins",
    skillsCount: "5 Habilidades",
    description: "La más elegida de la Panza Army. Habilidades de sabotaje directo de controles físicos y gatillo en pleno PUBG.",
    includedSkills: ["!invertir (WASD al revés por 10s)", "!disparar (Gatillo loco)", "Volumen x2", "Invertir Mouse"],
    purchaseUrl: "https://dixper.gg/pipa_arg",
    badge: "MÁS POPULAR",
    highlight: true,
  },
  {
    id: "crate-oro",
    name: "Caja de Oro (Pesadilla In-Ear)",
    tier: "oro",
    priceUsd: "$8.99 USD",
    priceArs: "~$10.800 ARS",
    coins: "800 Coins",
    skillsCount: "10 Habilidades Legendarias",
    description: "Destrucción total garantizada. Provoca screamers a 100% de volumen en sus Shure SE215 y desarme completo.",
    includedSkills: ["!screamer (100% volumen)", "!dropear (Tirar armas y chaleco)", "Pantalla Negra", "Controles Congelados"],
    purchaseUrl: "https://dixper.gg/pipa_arg",
    badge: "MÁXIMO DAÑO",
  },
];

export const WEEZYX_PACKS: WeezyxPack[] = [
  {
    id: "wzx-soundboard",
    name: "Audio Soundboard Clásico",
    priceArs: "Desde $150 ARS",
    priceUsd: "$0.25 USD",
    description: "Dispará audios clásicos de la Panza Army (!dalegordo, !quehizo, !pelotu2, !boca) al instante por el stream.",
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    tag: "INSTANTÁNEO",
  },
  {
    id: "wzx-tts",
    name: "Texto a Voz (TTS Robot)",
    priceArs: "Desde $250 ARS",
    priceUsd: "$0.40 USD",
    description: "Escribí tu mensaje o descanso y una voz robotizada lo leerá en voz alta sin baneo durante el directo.",
    characterLimit: "Hasta 250 caracteres",
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    tag: "SIN CENSURA",
    badge: "DESCANSO PURO",
  },
  {
    id: "wzx-voice",
    name: "Tu Propia Nota de Voz",
    priceArs: "Desde $450 ARS",
    priceUsd: "$0.75 USD",
    description: "Grabá un mensaje con tu micrófono y tu voz real saldrá por los parlantes del stream en vivo.",
    characterLimit: "Hasta 15 segundos",
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    tag: "VOZ REAL",
    badge: "100% INBANEABLE",
  },
];

export interface TwitchChannelReward {
  id: string;
  title: string;
  cost: number;
  costFormatted: string;
  category: "troll_ingame" | "stream" | "chat" | "status";
  categoryLabel: string;
  color: string;
  iconName: "Droplets" | "Users" | "Lock" | "Sparkles" | "Target" | "Smile" | "Music" | "Clock" | "Crosshair" | "Skull" | "Bomb" | "Repeat" | "EyeOff" | "MicOff" | "Crown" | "Shield";
  description: string;
  whatItDoes: string;
  pubgImpact?: string;
  purchaseUrl: string;
}

export const TWITCH_CHANNEL_REWARDS: TwitchChannelReward[] = [
  {
    id: "tw-awa",
    title: "awa",
    cost: 500,
    costFormatted: "500",
    category: "stream",
    categoryLabel: "INTERACCIÓN",
    color: "#008080",
    iconName: "Droplets",
    description: "Obliga a PIPAA a hidratarse y tomar agua en vivo.",
    whatItDoes: "Pausa el mate o la ranked para pegarle un trago a la botella y no deshidratarse.",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-diadesub",
    title: "Dia de sub",
    cost: 800,
    costFormatted: "800",
    category: "status",
    categoryLabel: "COMUNIDAD",
    color: "#5c2a82",
    iconName: "Users",
    description: "Lugar asegurado para jugar partidas comunitarias con PIPAA.",
    whatItDoes: "Entrás directo a la sala personalizada de PUBG o al squad en el día especial de subs.",
    pubgImpact: "Slot reservado en squad",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-desbloquear-emote",
    title: "Desbloquear un emoticono de...",
    cost: 1000,
    costFormatted: "1.000",
    category: "chat",
    categoryLabel: "CHAT",
    color: "#6b1196",
    iconName: "Lock",
    description: "Desbloqueo temporal de un emote exclusivo de suscriptor durante 24 horas.",
    whatItDoes: "Podés spamear un emote de tier alto en el chat aunque no tengas la sub de ese nivel.",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-modificar-emote",
    title: "Modificar un emoticono",
    cost: 1100,
    costFormatted: "1.100",
    category: "chat",
    categoryLabel: "CHAT",
    color: "#00d632",
    iconName: "Sparkles",
    description: "Aplica modificaciones visuales a un emote del canal en el chat.",
    whatItDoes: "Customiza cosméticamente los emotes de la Panza Army en tus mensajes del chat.",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-reto",
    title: "RETO",
    cost: 5000,
    costFormatted: "5.000",
    category: "troll_ingame",
    categoryLabel: "TROLL IN-GAME",
    color: "#9b0070",
    iconName: "Target",
    description: "Proponé un desafío o reto in-game a PIPAA para la partida en curso.",
    whatItDoes: "Jugar toda la ronda a escopeta, rushear sin chaleco, cruzar el puente a pie o hacer una jugada insana.",
    pubgImpact: "Condiciona el estilo de juego en la partida",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-mauribailando",
    title: "mauribailando",
    cost: 10000,
    costFormatted: "10.000",
    category: "stream",
    categoryLabel: "STREAM",
    color: "#f5ba42",
    iconName: "Smile",
    description: "Pone el clip meme de Mauri bailando en la pantalla del directo.",
    whatItDoes: "Festejo visual clásico de la Panza Army cuando el squad gana o clava una jugada épica.",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-cancion",
    title: "PONER UNA CANCION",
    cost: 10000,
    costFormatted: "10.000",
    category: "stream",
    categoryLabel: "MÚSICA",
    color: "#002699",
    iconName: "Music",
    description: "Elegí la siguiente canción que sonará por los parlantes del stream.",
    whatItDoes: "Agrega tu tema musical favorito a la cola de reproducción en vivo.",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-timeout",
    title: "TIME OUT",
    cost: 10000,
    costFormatted: "10.000",
    category: "chat",
    categoryLabel: "CHAT",
    color: "#9e8ecc",
    iconName: "Clock",
    description: "Mandá al rincón a pensar a cualquier espectador del chat por 60 segundos.",
    whatItDoes: "Aplica un muteo temporal de 1 minuto al usuario que elijas en el chat de Twitch.",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-soltar-arma",
    title: "SOLTAR UN ARMA",
    cost: 15000,
    costFormatted: "15.000",
    category: "troll_ingame",
    categoryLabel: "TROLL IN-GAME",
    color: "#381461",
    iconName: "Crosshair",
    description: "PIPAA debe soltar inmediatamente una de sus armas principales al suelo.",
    whatItDoes: "Se queda completamente desarmado o a secundaria en pleno tiroteo de PUBG.",
    pubgImpact: "Desarme forzado en pleno combate",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-head-companero",
    title: "headauncompañero",
    cost: 15000,
    costFormatted: "15.000",
    category: "troll_ingame",
    categoryLabel: "FUEGO AMIGO",
    color: "#e62222",
    iconName: "Skull",
    description: "Obliga a PIPAA a pegarle un tiro a la cabeza a un compañero de su squad.",
    whatItDoes: "Headshot instantáneo a Mauri, CristianLa12 o Sapo en medio de la partida.",
    pubgImpact: "Fuego amigo directo al squad",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-utilidades",
    title: "Utilidades",
    cost: 15000,
    costFormatted: "15.000",
    category: "troll_ingame",
    categoryLabel: "TROLL IN-GAME",
    color: "#a3b827",
    iconName: "Bomb",
    description: "Obliga a PIPAA a tirar o vaciar todas sus granadas, humos y curaciones al piso.",
    whatItDoes: "Pierde todo el inventario táctico y queda vulnerable en las últimas zonas.",
    pubgImpact: "Descarte de botiquines y granadas",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-espejo",
    title: "ESPEJO",
    cost: 15000,
    costFormatted: "15.000",
    category: "troll_ingame",
    categoryLabel: "TROLL IN-GAME",
    color: "#2cb3c9",
    iconName: "Repeat",
    description: "Modo espejo: jugar con los controles de movimiento o cámara invertidos.",
    whatItDoes: "Provoca desorientación motriz total al rushear o conducir vehículos.",
    pubgImpact: "Inversión de vista y movilidad",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-ctrl-u",
    title: "CTRL+U 3 minutos",
    cost: 20000,
    costFormatted: "20.000",
    category: "troll_ingame",
    categoryLabel: "TROLL HARDCORE",
    color: "#002bb8",
    iconName: "EyeOff",
    description: "Oculta el HUD completo de PUBG durante 3 minutos seguidos con Ctrl+U.",
    whatItDoes: "Juega a ciegas: sin punto de mira, sin minimapa, sin barra de vida ni indicador de munición.",
    pubgImpact: "Cero interfaz gráfica durante 180 segundos",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-mutear",
    title: "Mutear a alguien de...",
    cost: 30000,
    costFormatted: "30.000",
    category: "stream",
    categoryLabel: "DISCORD",
    color: "#b39ddb",
    iconName: "MicOff",
    description: "Silencia la voz de un compañero en la llamada de Discord durante el stream.",
    whatItDoes: "El compañero se queda mudo sin poder dar info de los enemigos.",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-vip",
    title: "VIP EN EL CANAL",
    cost: 400000,
    costFormatted: "400.000",
    category: "status",
    categoryLabel: "RANGO VIP",
    color: "#8e24aa",
    iconName: "Crown",
    description: "Insignia y estatus VIP oficial permanente en el canal de Twitch de PIPAA.",
    whatItDoes: "Medalla de diamante VIP en el chat, inmunidad al modo lento y reconocimiento en la Panza Army.",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
  {
    id: "tw-mod",
    title: "MOD",
    cost: 800000,
    costFormatted: "800.000",
    category: "status",
    categoryLabel: "RANGO MODERADOR",
    color: "#2e7d32",
    iconName: "Shield",
    description: "El mayor honor del canal: la espada verde de Moderador oficial de Twitch.",
    whatItDoes: "Permisos de moderación de chat, timeouts, baneos y gestión de la comunidad en directo.",
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
  },
];

// Alias para compatibilidad
export const TWITCH_BOUNTIES = TWITCH_CHANNEL_REWARDS;

export const COMMANDS_DATA: CommandItem[] = [
  // ── 1. TROLLS & BAITS ──
  {
    id: "dinero",
    name: "!dinero",
    category: "baits",
    tag: "BAIT SUPREMO",
    shortDesc: "El engaño más legendario del canal para los nuevos.",
    whatItDoes: "Cuando un espectador escribe !dinero esperando recibir puntos o recompensas virtuales, el bot le responde insultándolo amistosamente.",
    whyItExists: "El comando !puntos del canal dice falsamente: 'Si querés ganar más puntos hacela fácil, con el comando !dinero podes ganar miles!'. Todos los que llegan nuevos caen.",
    botResponse: "Te la creiste puto !",
    isBait: true,
    botType: "Nightbot",
    syntaxExample: "!dinero",
  },
  {
    id: "ban",
    name: "!ban",
    category: "baits",
    tag: "FALSO BANEO",
    shortDesc: "Simulación de baneo por no entrar en la pantalla.",
    whatItDoes: "Genera una notificación fingiendo banear al usuario que ejecutó el comando o al mencionado.",
    whyItExists: "Es parte de la temática 'Panza Army': el bot acusa al usuario de ser tan gordo que desborda la pantalla del stream.",
    botResponse: "[usuario] ha sido baneado porque no cabe en la pantalla! Deja de comer gordo!! pastaThat",
    isBait: true,
    botType: "Nightbot",
    syntaxExample: "!ban",
  },
  {
    id: "tirarban",
    name: "!tirarban",
    category: "baits",
    tag: "ENVIAR AL GULAG",
    shortDesc: "Manda a un usuario al Gulag por maleta.",
    whatItDoes: "Simula expulsar al usuario seleccionado directamente al Gulag por jugar mal o manquear.",
    whyItExists: "Remate cómico contra los moderadores o viewers cuando erran tiros o hacen jugadas dudosas.",
    botResponse: "[usuario] Se fue directo al GULAG por ser terrible MALETA HeyGuys",
    botType: "Nightbot",
    syntaxExample: "!tirarban @usuario",
  },
  {
    id: "mod",
    name: "!mod",
    category: "baits",
    tag: "TRAMPA MOD",
    shortDesc: "Baneo inmediato para quien pida ser moderador.",
    whatItDoes: "Advierte y asusta a los espectadores que preguntan cómo ser moderadores del canal.",
    whyItExists: "En Twitch y Kick siempre entran espectadores pidiendo moderador; la regla de PIPAA es automática y tajante.",
    botResponse: "EL QUE PIDE MOD SE VA BANEADO !!",
    isBait: true,
    botType: "Nightbot",
    syntaxExample: "!mod",
  },
  {
    id: "cerra",
    name: "!cerra",
    category: "baits",
    tag: "CALLAR USUARIO",
    shortDesc: "Manda a callar a alguien que está hablando de más.",
    whatItDoes: "Envía un mensaje formateado en cursiva (/me) ordenando al usuario taggeado cerrar la boca.",
    whyItExists: "Usado masivamente cuando alguien del chat o del squad empieza a quejarse o tirar excusas tras morir.",
    botResponse: "/me CERRA EL ORTO [usuario]",
    botType: "Nightbot",
    syntaxExample: "!cerra @usuario",
  },
  {
    id: "datazo",
    name: "!datazo",
    category: "baits",
    tag: "SARCASMO PURO",
    shortDesc: "Ironía directa para opiniones que nadie pidió.",
    whatItDoes: "Aclara sarcásticamente que nadie había solicitado esa información o comentario.",
    whyItExists: "Para responder a espectadores que analizan jugadas como si fueran analistas de esports.",
    botResponse: "Que BUEN dato mi pana! la proxima te lo pedimos.",
    botType: "Nightbot",
    syntaxExample: "!datazo",
  },
  {
    id: "mira",
    name: "!mira",
    category: "baits",
    tag: "JUEGO DE PALABRAS",
    shortDesc: "Troleo para el que pregunta por la mirilla/crosshair.",
    whatItDoes: "En vez de dar la configuración de la mira, insulta cariñosamente al espectador.",
    whyItExists: "Cientos de personas preguntan a diario qué mira usa in-game. PIPAA creó este comando para descansarlos (para la real existe !mira2).",
    botResponse: "Mira un pelotudo más...",
    isBait: true,
    botType: "Nightbot",
    syntaxExample: "!mira",
  },
  {
    id: "tela",
    name: "!tela",
    category: "baits",
    tag: "DOBLE SENTIDO",
    shortDesc: "Remate callejero al que dice 'tela'.",
    whatItDoes: "Completa la frase con una clásica rima argentina de doble sentido.",
    whyItExists: "Puntazo rápido cuando alguien pregunta qué tela tiene el mousepad o la manga.",
    botResponse: "Telacomesentera pipaaKappa",
    botType: "Nightbot",
    syntaxExample: "!tela",
  },
  {
    id: "sorpresa",
    name: "!sorpresa",
    category: "baits",
    tag: "RIMA FAMILIAR",
    shortDesc: "Rima sorpresa de barrio.",
    whatItDoes: "Responde con un chiste familiar directo.",
    whyItExists: "Típico humor de barrio de los directos de PIPAA cuando anuncian un sorteo o sorpresa.",
    botResponse: "Tu mamá me besa la cabeza",
    botType: "Nightbot",
    syntaxExample: "!sorpresa",
  },
  {
    id: "baneado",
    name: "!baneado",
    category: "baits",
    tag: "REGLAMENTO",
    shortDesc: "Advertencia oficial sobre el humor del chat.",
    whatItDoes: "Explica a la gente nueva que los bans falsos y las burlas son chistes comunitarios y nadie debe ofenderse.",
    whyItExists: "Evita que los espectadores sensibles se enojen con los moderadores cuando les hacen bromas pesadas.",
    botResponse: "SI ALGUN MOD TE BANEA (SIN MOTIVO) O PORQUE SE ESTA HACIENDO ALGUN CHISTE.. NO TE ENOJES ES SOLO PARA LAS RISAS SIEMPRE SE HACE EN ESTE CHAT TODOS LOS MOD JODEN ASI. NO SEAS CULEA",
    botType: "Nightbot",
    syntaxExample: "!baneado",
  },

  // ── 2. RULETA & SOCIAL CHAT (STREAMELEMENTS) ──
  {
    id: "ccm",
    name: "!ccm",
    category: "ruleta",
    tag: "CASAR COJER MATAR",
    shortDesc: "El juego social definitivo con 3 chatters aleatorios.",
    whatItDoes: "Selecciona aleatoriamente tres usuarios conectados en ese momento y asigna a cada uno un destino diferente.",
    whyItExists: "Genera caos instantáneo en el chat al involucrar espectadores al azar en situaciones comprometidas.",
    botResponse: "$(user) se casó con @Chino_PUBG, le rompio el culo a @MauriCabj y le pego un tiro a @Sapo_Arg",
    botType: "StreamElements",
    syntaxExample: "!ccm",
  },
  {
    id: "meentra",
    name: "!meentra",
    category: "ruleta",
    tag: "RULETA EN CM",
    shortDesc: "Calcula aleatoriamente la capacidad del usuario.",
    whatItDoes: "Genera una cifra en centímetros al azar asociada al espectador que escribió el comando.",
    whyItExists: "Uno de los comandos más spameados durante las madrugadas en el chat.",
    botResponse: "A @GamerArgento le entran 24.8 cm.",
    botType: "StreamElements",
    syntaxExample: "!meentra",
  },
  {
    id: "leentra",
    name: "!leentra",
    category: "ruleta",
    tag: "RULETA A UN TERCERO",
    shortDesc: "Averigua la capacidad de un chatter aleatorio.",
    whatItDoes: "Toma a otro espectador al azar del chat y le asigna una medida.",
    whyItExists: "Permite trollear a amigos y moderadores que están mirando el stream sin escribir.",
    botResponse: "A @Alan_Troll le entran 31.2 cm.",
    botType: "StreamElements",
    syntaxExample: "!leentra",
  },
  {
    id: "memide",
    name: "!memide",
    category: "ruleta",
    tag: "MEDIDOR VIRTUAL",
    shortDesc: "Mide el tamaño virtual del usuario en vivo.",
    whatItDoes: "Devuelve un número aleatorio entre 1 y 40 cm para el usuario.",
    whyItExists: "Competencia de ego virtual recurrente entre los seguidores de la Panza Army.",
    botResponse: "A @PanzaFan le mide 19 cm.",
    botType: "Nightbot",
    syntaxExample: "!memide",
  },
  {
    id: "chele",
    name: "!chele",
    category: "ruleta",
    tag: "TROLL RANDOM",
    shortDesc: "Ataque aleatorio a otro espectador del chat.",
    whatItDoes: "Conecta al usuario con otro espectador tomado al azar mediante una acción gráfica graciosa.",
    whyItExists: "Humor característico y sin filtro de las transmisiones nocturnas de PUBG.",
    botResponse: "@PipaFan le tiro un lechazo a @Cristian12",
    botType: "StreamElements",
    syntaxExample: "!chele",
  },
  {
    id: "hermana",
    name: "!hermana",
    category: "ruleta",
    tag: "DESCANSO FAMILIAR",
    shortDesc: "Involucra a la hermana de un usuario al azar.",
    whatItDoes: "Selecciona un chatter activo y le adjudica un romance prohibido con el ejecutor.",
    whyItExists: "El clásico descanso entre argentinos que nunca falta en el chat de PIPAA.",
    botResponse: "@Nico_Arg le comió la hermana a @Sapo_Verde",
    botType: "StreamElements",
    syntaxExample: "!hermana",
  },
  {
    id: "prima",
    name: "!prima",
    category: "ruleta",
    tag: "DESCANSO PRIMA",
    shortDesc: "Variante del comando familiar apuntando a la prima.",
    whatItDoes: "Genera el meme de comerle la prima a un espectador al azar.",
    whyItExists: "Muy utilizado cuando alguien en el squad menciona a sus parientes.",
    botResponse: "@Lucas_01 le come la prima a @BdMi_Fan",
    botType: "StreamElements",
    syntaxExample: "!prima",
  },
  {
    id: "japi",
    name: "!japi",
    category: "ruleta",
    tag: "TROLL FÍSICO",
    shortDesc: "Agarrada virtual a un chatter random.",
    whatItDoes: "Conecta a dos usuarios del chat en una situación cómica.",
    whyItExists: "Spam recurrente en los momentos de mayor euforia o victorias de partidas.",
    botResponse: "@Mauri le agarro la japi a @Alanitox",
    botType: "StreamElements",
    syntaxExample: "!japi",
  },
  {
    id: "teta",
    name: "!teta",
    category: "ruleta",
    tag: "TROLL RANDOM",
    shortDesc: "Troleo físico a un espectador al azar.",
    whatItDoes: "El bot selecciona un usuario al azar para la interacción.",
    whyItExists: "Parte de la batería de comandos de interacción bizarra de StreamElements.",
    botResponse: "@Gordo_07 le agarro la teta a @Pame_Ok",
    botType: "StreamElements",
    syntaxExample: "!teta",
  },
  {
    id: "amor",
    name: "!amor",
    category: "ruleta",
    tag: "COMPATIBILIDAD",
    shortDesc: "Calcula el porcentaje de amor entre dos personas.",
    whatItDoes: "Devuelve un número del 0% al 100% de compatibilidad amorosa.",
    whyItExists: "Para shippear a PIPAA con otros streamers o a dos moderadores del chat.",
    botResponse: "Entre @Pipa_Arg y @CristianLa12 hay 89% de amor GivePLZ TakeNRG",
    botType: "Nightbot",
    syntaxExample: "!amor @usuario",
  },
  {
    id: "pajin",
    name: "!pajin",
    category: "ruleta",
    tag: "CONTADOR DIARIO",
    shortDesc: "Averigua cuántas veces pecó el usuario en el día.",
    whatItDoes: "Genera una cifra cómica de veces que el usuario taggeado estuvo en privado.",
    whyItExists: "Típica burla cuando alguien tarda en responder o llega tarde al stream.",
    botResponse: "Hoy @Alanitox se hizo 6 pajas",
    botType: "Nightbot",
    syntaxExample: "!pajin @usuario",
  },
  {
    id: "vino",
    name: "!vino",
    category: "ruleta",
    tag: "MEDIDOR DE TETRA",
    shortDesc: "Calcula las cajas de vino consumidas.",
    whatItDoes: "Devuelve un número aleatorio de cajas de vino tomadas por el usuario.",
    whyItExists: "En honor a las noches de stream borracho y los sábados de 'Stream Drink'.",
    botResponse: "@Pipa_Arg se tomó 14 cajas de vino BrokeBack",
    botType: "Nightbot",
    syntaxExample: "!vino",
  },

  // ── 3. LORE & SQUAD DE LA PANZA ARMY ──
  {
    id: "teoria",
    name: "!teoria",
    category: "lore",
    tag: "TEORÍA DEL SAPO",
    shortDesc: "La hipótesis científica sobre las 3 neuronas de Sapo.",
    whatItDoes: "Relata la tesis de PIPAA sobre por qué su compañero Sapo siempre da callouts erróneos.",
    whyItExists: "Sapo es uno de sus amigos y compañeros más históricos; cada vez que tira una call falsa, el chat escribe !teoria.",
    botResponse: "En este canal manejamos la teoria de que a la hora de callear, las 3 neuronas del sapo manejan solo 2 opciones. Opcion 1: 0 info (usa su poca concentracion para intentar atinar una bala). Opcion 2: dar informacion falsa o alucinada para parecerse a su idolo Pipa y tirar calls que en su cabeza son reales pero son nefastas.",
    botType: "Nightbot",
    syntaxExample: "!teoria",
  },
  {
    id: "cristian",
    name: "!cristian",
    category: "lore",
    tag: "EL LOOTER ETERNO",
    shortDesc: "El grito de auxilio cuando Cristian no para de agarrar cosas.",
    whatItDoes: "Imprime la queja legendaria de PIPAA contra su compañero de squad.",
    whyItExists: "CristianLa12 es conocido por quedarse looteando casas y cascos mientras el resto del equipo está en tiroteo pleno.",
    botResponse: "DEJA DE LOOOOOOOOOOOTEAR",
    botType: "Nightbot",
    syntaxExample: "!cristian",
  },
  {
    id: "sanguche",
    name: "!sanguche",
    category: "lore",
    tag: "AFK DE COMIDA",
    shortDesc: "Cuando PIPAA abandona la cámara para ir a la heladera.",
    whatItDoes: "Avisa al chat que el streamer se fue a preparar comida.",
    whyItExists: "PIPAA suele dejar la partida en marcha o entre rankeds para armarse un sanguche en plena transmisión.",
    botResponse: "EL GORDO FUE A BUSCAR UN SANGUCHE YA VUELVE..",
    botType: "Nightbot",
    syntaxExample: "!sanguche",
  },
  {
    id: "helado",
    name: "!helado",
    category: "lore",
    tag: "AFK DE HELADO",
    shortDesc: "Segunda variante del escape a la cocina.",
    whatItDoes: "Explica la ausencia del streamer durante las noches de calor.",
    whyItExists: "Famoso por comer potes de helado de kilo mientras mira replays y habla con el chat.",
    botResponse: "EL GORDO FUE A BUSCAR MAS HELADO YA VUELVE..",
    botType: "Nightbot",
    syntaxExample: "!helado",
  },
  {
    id: "eructo",
    name: "!eructo",
    category: "lore",
    tag: "CONTADOR EN VIVO",
    shortDesc: "Lleva la cuenta de eructos en el stream.",
    whatItDoes: "Incrementa un contador automático cada vez que PIPAA suelta un eructo en el micrófono.",
    whyItExists: "Cero filtro en el stream: los viewers festejan y contabilizan cada gas como si fuera un gol.",
    botResponse: "PIPA eructó 184 veces pipaaAHHHHH",
    botType: "Nightbot",
    syntaxExample: "!eructo",
  },
  {
    id: "balas",
    name: "!balas",
    category: "lore",
    tag: "MANQUEADA OFICIAL",
    shortDesc: "Contador de balas erradas consecutivas.",
    whatItDoes: "Se burla de la precisión de PIPAA cuando descarga un cargador entero sin acertar.",
    whyItExists: "A pesar de ser pro player, los sprays fallidos a 2 metros quedan inmortalizados con este comando.",
    botResponse: "PIPA VA ERRANDO SU BALA NUMERO 37",
    botType: "Nightbot",
    syntaxExample: "!balas",
  },
  {
    id: "vivido",
    name: "!vivido",
    category: "lore",
    tag: "SUPER VIVIYIN",
    shortDesc: "Cuando se activa el modo ultracompetitivo y serio.",
    whatItDoes: "Advierte que se apagó el show y comenzó el entrenamiento hardcore.",
    whyItExists: "En torneos oficiales y scrims de alto nivel, PIPAA mutea la música, apaga la webcam y se enfoca al 100%.",
    botResponse: "El gordito activo el modo super saiyajin ultra vivido (super viviyin), no hay cam, ni voces, solo tiros y muertes pipaaFacha pipaaLoco",
    botType: "Nightbot",
    syntaxExample: "!vivido",
  },
  {
    id: "chat",
    name: "!chat",
    category: "lore",
    tag: "MONITOR APAGADO",
    shortDesc: "Por qué PIPAA no lee el chat durante las partidas.",
    whatItDoes: "Informa con humor que durante las partidas clave tiene los monitores apagados.",
    whyItExists: "Los viewers se quejan de que no lee las donaciones mientras está en medio de un tiroteo 1v4.",
    botResponse: "No va a estar leyendo el chat durante las scrims o los torneos, apagó el monitor así se concentra, el principal también claramente pipaaMamado",
    botType: "Nightbot",
    syntaxExample: "!chat",
  },
  {
    id: "gordogarca",
    name: "!gordogarca",
    category: "lore",
    tag: "MEME DE RULETAS",
    shortDesc: "Acusación comunitaria por ruletas de subs adeudadas.",
    whatItDoes: "Denuncia en broma que el streamer prometió premios y ruletas y no las giró.",
    whyItExists: "En los extensibles suele prometer giros de ruleta por suscripciones y a veces se le acumulan decenas.",
    botResponse: "el gordo es un garca, promete ruleta por sub y despues no las da, reportenlo",
    botType: "Nightbot",
    syntaxExample: "!gordogarca",
  },
  {
    id: "pipa",
    name: "!pipa",
    category: "lore",
    tag: "AUTOCRÍTICA",
    shortDesc: "Definición oficial del dueño del canal.",
    whatItDoes: "Describe a PIPAA con máxima honestidad y cero ego.",
    whyItExists: "Auto-descanso creado por el propio streamer para que nadie se tome nada en serio.",
    botResponse: "un pelotudo con 2 de iq",
    botType: "Nightbot",
    syntaxExample: "!pipa",
  },
  {
    id: "alanitox",
    name: "!alanitox",
    category: "lore",
    tag: "DESCANSO A ALAN",
    shortDesc: "El ataque cariñoso a su amigo Alan.",
    whatItDoes: "Describe el perfil del compañero del squad.",
    whyItExists: "Alan es uno de los jugadores que más tiltea a PIPAA en las rankeds diarias.",
    botResponse: "pito chico, virgen y hater ahh y MALOOO.",
    botType: "Nightbot",
    syntaxExample: "!alanitox",
  },

  // ── 4. IN-GAME TROLLS & DIXPER (HABILIDADES COMPRABLES) ──
  {
    id: "dixper-invert",
    name: "!invertir (Dixper)",
    category: "ingame",
    tag: "DIXPER · CONTROLES",
    shortDesc: "Invierte las teclas WASD de PIPAA durante 10 segundos en plena partida.",
    whatItDoes: "El cliente Dixper instalado en la PC de PIPAA invierte el teclado: la W va para atrás y la A para la derecha, arruinándole el movimiento o manejo de vehículos.",
    whyItExists: "Es una de las cartas más troll de Dixper; la gente la activa cuando PIPAA va a toda velocidad en auto por el puente de Erangel.",
    botResponse: "[DIXPER ACTIVADO: Controles invertidos durante 10s - ¡Cuidado con el volante!]",
    botType: "Dixper / In-Game",
    isPurchasable: true,
    purchaseUrl: "https://dixper.gg/pipa_arg",
    priceLabel: "Caja Dixper (~$2.400 ARS)",
    priceArs: "~$2.400 ARS",
    priceUsd: "$1.99 USD",
    priceCoins: "150 Coins",
    trollLevel: 5,
    hardwareTarget: "Teclado WASD (Inversión Física)",
    paymentMethods: ["Mercado Pago", "Tarjeta Débito/Crédito", "PayPal", "Dixper Coins"],
    triggerGuide: "El momento de oro es cuando conduce un vehículo a máxima velocidad hacia la zona o cuando entra a rushear un departamento cerrado.",
    purchasePlatform: "dixper.gg/pipa_arg",
    syntaxExample: "Lanzar carta en Dixper",
  },
  {
    id: "dixper-fire",
    name: "!disparar (Dixper)",
    category: "ingame",
    tag: "DIXPER · DELATAR",
    shortDesc: "Fuerza a PIPAA a vaciar el cargador automáticamente.",
    whatItDoes: "Obliga al mouse a disparar ráfagas sin que PIPAA lo toque, delatando la posición del squad en las rotaciones silenciosas de PUBG.",
    whyItExists: "Ideal cuando están escondidos en un arbusto o aguantando una casa en la fase 5.",
    botResponse: "[DIXPER ACTIVADO: Spray involuntario - ¡Posición delatada!]",
    botType: "Dixper / In-Game",
    isPurchasable: true,
    purchaseUrl: "https://dixper.gg/pipa_arg",
    priceLabel: "Caja Dixper (~$2.400 ARS)",
    priceArs: "~$2.400 ARS",
    priceUsd: "$1.99 USD",
    priceCoins: "150 Coins",
    trollLevel: 4,
    hardwareTarget: "Mouse / Gatillo (Spray Automático)",
    paymentMethods: ["Mercado Pago", "Tarjeta Débito/Crédito", "PayPal", "Dixper Coins"],
    triggerGuide: "Lanzalo cuando el squad esté haciendo una rotación sigilosa agachados entre árboles o aguantando la fase final.",
    purchasePlatform: "dixper.gg/pipa_arg",
    syntaxExample: "Lanzar carta en Dixper",
  },
  {
    id: "dixper-drop",
    name: "!dropear (Dixper)",
    category: "ingame",
    tag: "DIXPER · DESARME",
    shortDesc: "Le hace tirar el arma principal al suelo.",
    whatItDoes: "Abre el inventario y dropea el arma o todas las balas del 7.62 que tenga equipadas.",
    whyItExists: "Causa ataques de risa cuando entra a una casa a pushear y se da cuenta que tiene las manos vacías.",
    botResponse: "[DIXPER ACTIVADO: Desarme forzado - Beryl M762 al piso]",
    botType: "Dixper / In-Game",
    isPurchasable: true,
    purchaseUrl: "https://dixper.gg/pipa_arg",
    priceLabel: "Caja Plata (~$6.000 ARS)",
    priceArs: "~$6.000 ARS",
    priceUsd: "$4.99 USD",
    priceCoins: "400 Coins",
    trollLevel: 5,
    hardwareTarget: "Inventario (Desarme Completo)",
    paymentMethods: ["Mercado Pago", "Tarjeta Débito/Crédito", "PayPal", "Dixper Coins"],
    triggerGuide: "Detonalo justo en el segundo previo a que asome la cabeza para dispararle a un enemigo que viene corriendo.",
    purchasePlatform: "dixper.gg/pipa_arg",
    syntaxExample: "Lanzar carta en Dixper",
  },
  {
    id: "dixper-screamer",
    name: "!screamer (Dixper)",
    category: "ingame",
    tag: "DIXPER · SUSTO",
    shortDesc: "Un susto visual y sonoro a pantalla completa con 100% de volumen.",
    whatItDoes: "Lanza una imagen de terror en la pantalla con un grito estridente por los auriculares Shure SE215.",
    whyItExists: "PIPAA juega con in-ears aislantes de sonido; los screamers lo hacen saltar de la silla.",
    botResponse: "[DIXPER ACTIVADO: Screamer en pantalla - ¡Salto de la silla garantizado!]",
    botType: "Dixper / In-Game",
    isPurchasable: true,
    purchaseUrl: "https://dixper.gg/pipa_arg",
    priceLabel: "Caja Oro (~$10.800 ARS)",
    priceArs: "~$10.800 ARS",
    priceUsd: "$8.99 USD",
    priceCoins: "800 Coins",
    trollLevel: 5,
    hardwareTarget: "Auriculares Shure SE215 (100% Vol) & Pantalla",
    paymentMethods: ["Mercado Pago", "Tarjeta Débito/Crédito", "PayPal", "Dixper Coins"],
    triggerGuide: "El momento ideal es cuando está concentrado apuntando con mira x8 aguantando la respiración sin hablar.",
    purchasePlatform: "dixper.gg/pipa_arg",
    syntaxExample: "Lanzar carta en Dixper",
  },
  {
    id: "audios-weezyx",
    name: "!audios",
    category: "sonidos",
    tag: "WEEZYX TTS",
    shortDesc: "Mandá audios de voz o puteadas directas al stream en vivo (inbaneable).",
    whatItDoes: "Envía un mensaje de voz o texto sintetizado por voz que suena en el stream de PIPAA sin censura ni filtro.",
    whyItExists: "Comando oficial del canal para que los espectadores manden descansos personalizados o arengas al squad.",
    botResponse: "Ahora podes mandarme audios (putearme, mamarla, decirle cosas a los pibes, lo que quieras, sos inbaneable) al stream entrando a weezyx.com/t/pipa_arg",
    botType: "Sound Alert",
    isPurchasable: true,
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    priceLabel: "Desde $150 ARS",
    priceArs: "Desde $150 ARS",
    priceUsd: "$0.25 USD",
    trollLevel: 4,
    hardwareTarget: "Audio del Stream (Sin Filtros)",
    paymentMethods: ["Mercado Pago", "Ualá", "CVU / Débito", "Tarjeta de Crédito"],
    triggerGuide: "Mandalo en medio de un debate acalorado del squad o cuando PIPAA se queje de la falta de balas.",
    purchasePlatform: "weezyx.com/t/pipa_arg",
    syntaxExample: "weezyx.com/t/pipa_arg",
  },
  {
    id: "trollbot2",
    name: "!trollbot2",
    category: "ingame",
    tag: "COMANDOS DIXPER",
    shortDesc: "Cómo usar e intercambiar los comandos de tortura en directo.",
    whatItDoes: "Instruye a los espectadores cómo comprar y guardar comandos troll de Bits para activárselos en el peor momento.",
    whyItExists: "PIPAA utiliza la plataforma Dixper / Trollbot para que el público active sustos, ráfagas involuntarias o pantalla invertida.",
    botResponse: "En caso de que quieras canjear los 100 bits para el head pero usar el disparo en otro momento, escribí: !use buy 100 CHEER100 // Para regalar el comando troll a otro: !use gift @user 100 CHEER100",
    botType: "Dixper / In-Game",
    isPurchasable: true,
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
    priceLabel: "100 Bits (~$1.700 ARS)",
    priceArs: "~$1.700 ARS",
    priceUsd: "$1.40 USD",
    priceCoins: "100 Bits",
    trollLevel: 4,
    hardwareTarget: "Disparo In-Game / Canal Twitch",
    paymentMethods: ["Twitch Bits", "Amazon Pay", "PayPal"],
    triggerGuide: "Compralo y guardalo con '!use buy 100 CHEER100', luego disparalo en el momento de mayor tensión.",
    purchasePlatform: "Twitch Cheer / Bits",
    syntaxExample: "!trollbot2",
  },
  {
    id: "head",
    name: "!head",
    category: "ingame",
    tag: "FRIENDLY FIRE",
    shortDesc: "Lista de precios de fuego amigo en el squad.",
    whatItDoes: "Muestra los costos en puntos o bits para ordenar una ejecución a un compañero de equipo en plena partida.",
    whyItExists: "Dinámica clave de sus streams: cuando un espectador junta puntos, puede obligar a un jugador a matar a otro.",
    botResponse: "Tenemos nueva promocion en el canal ademas de los puntos: 100 diamantes -> 1 head; 500 diamantes -> 1 knock; 1000000 diamantes -> Mata remata",
    botType: "Dixper / In-Game",
    isPurchasable: true,
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
    priceLabel: "100 Diamantes (Gratis)",
    priceArs: "Gratis con stream",
    priceUsd: "100 Diamantes",
    priceCoins: "100 Puntos",
    trollLevel: 5,
    hardwareTarget: "Fuego Amigo en Vivo (PUBG)",
    paymentMethods: ["Puntos de Canal Twitch (Gratis acumulando horas de stream)"],
    triggerGuide: "Canjealo cuando el Sapo o Cristian estén looteando tranquilos una caja de Airdrop.",
    purchasePlatform: "Puntos de Canal",
    syntaxExample: "!head",
  },
  {
    id: "lista",
    name: "!lista",
    category: "ingame",
    tag: "LISTA DE BLANCOS",
    shortDesc: "A quiénes se les puede dar un tiro en la cabeza.",
    whatItDoes: "Enumera a todos los jugadores habilitados para recibir daño por parte de la comunidad.",
    whyItExists: "Evita que le disparen a jugadores invitados que no forman parte de la joda interna.",
    botResponse: "Se puede canjear puntos por head a: CristianLa12, mauricabj, sapopp, Alan, fabri, Aguss2, Sayazera, p4me, bdmi y a cris xD",
    botType: "Dixper / In-Game",
    isPurchasable: true,
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
    priceLabel: "Puntos de Canal",
    priceArs: "Gratis con stream",
    priceUsd: "Puntos Twitch",
    trollLevel: 3,
    hardwareTarget: "Reglamento de Fuego Amigo",
    paymentMethods: ["Puntos de Canal Twitch"],
    triggerGuide: "Consultá la lista antes de gastar tus diamantes para asegurarte de que tu blanco esté jugando.",
    purchasePlatform: "Canal Twitch/Kick",
    syntaxExample: "!lista",
  },
  {
    id: "heads",
    name: "!heads",
    category: "ingame",
    tag: "MARCADOR DE BALAZOS",
    shortDesc: "Historial de disparos recibidos en el squad.",
    whatItDoes: "Lleva el tanteador acumulado de cuántos tiros en la cabeza se comió cada miembro del equipo.",
    whyItExists: "PIPAA casi siempre encabeza la tabla con más de 26 heads recibidos de sus propios compañeros.",
    botResponse: "mauri 2 | sapo tiene 4 heads | PIPAA tiene 26 heads | Pame 1 head | cristian 10",
    botType: "Dixper / In-Game",
    isPurchasable: true,
    purchaseUrl: "https://www.twitch.tv/pipa_arg",
    priceLabel: "Puntos de Canal",
    priceArs: "Gratis con stream",
    priceUsd: "Puntos Twitch",
    trollLevel: 2,
    hardwareTarget: "Estadísticas del Squad",
    paymentMethods: ["Puntos de Canal Twitch"],
    triggerGuide: "Mirá quién va perdiendo para sumar tu headshot al que más tiros tiene.",
    purchasePlatform: "Canal Twitch/Kick",
    syntaxExample: "!heads",
  },

  // ── 5. SOUNDBOARD / AUDIOS DEL STREAM ──
  {
    id: "sonidos",
    name: "!sonidos",
    category: "sonidos",
    tag: "CATÁLOGO DE AUDIOS",
    shortDesc: "El índice general de alertas sonoras del stream.",
    whatItDoes: "Muestra la lista de los más de 30 sonidos disponibles que la audiencia puede detonar en vivo.",
    whyItExists: "Permite a los espectadores saber qué comando de audio usar para asustar o festejar.",
    botResponse: "!quehizo !corre !fuck !gordo !tumama !dalegordo !monte !poneplay !ay !risabiel !pelotu2 !cuack !cuack2 !boca !aplauso !gei !grasa !noo !maleta !agus !bomberos !risa1 !risa2 !susto !acasa !laschicas",
    soundName: "Catálogo",
    botType: "Sound Alert",
    syntaxExample: "!sonidos",
  },
  {
    id: "dalegordo",
    name: "!dalegordo",
    category: "sonidos",
    tag: "AUDIO CLÁSICO",
    shortDesc: "Audio de arenga motivacional a los gritos.",
    whatItDoes: "Suena el mítico grito de aliento '¡Dale gordo, daleee!' cuando PIPAA queda en un 1v1.",
    whyItExists: "El audio más usado para alentar los Chicken Dinners o para burlarse cuando queda arrastrándose.",
    botResponse: "[Reproduciendo: ¡Dale gordo daleeeee!]",
    soundName: "Dale Gordo",
    botType: "Sound Alert",
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    priceLabel: "Audio Weezyx",
    purchasePlatform: "weezyx.com/t/pipa_arg",
    syntaxExample: "!dalegordo",
  },
  {
    id: "quehizo",
    name: "!quehizo",
    category: "sonidos",
    tag: "AUDIO ASOMBRO",
    shortDesc: "Reacción a una jugada incomprensible.",
    whatItDoes: "Suena el audio '¿Pero qué hizo? ¿Qué hizo este muchacho?'.",
    whyItExists: "Se detona cuando un rival o un miembro del squad comete un error insólito en la rotación.",
    botResponse: "[Reproduciendo: ¿¿Pero qué hizo??]",
    soundName: "Qué Hizo",
    botType: "Sound Alert",
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    priceLabel: "Audio Weezyx",
    purchasePlatform: "weezyx.com/t/pipa_arg",
    syntaxExample: "!quehizo",
  },
  {
    id: "pelotu2",
    name: "!pelotu2",
    category: "sonidos",
    tag: "AUDIO DESCANSO",
    shortDesc: "Remate al que se manda una macana.",
    whatItDoes: "Dispara el famoso audio argentino insultando con cariño.",
    whyItExists: "Frecuente cuando alguien se suicida con su propia granada o choca un vehículo.",
    botResponse: "[Reproduciendo: ¡Pero qué pelotudo!]",
    soundName: "Pelotudo",
    botType: "Sound Alert",
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    priceLabel: "Audio Weezyx",
    purchasePlatform: "weezyx.com/t/pipa_arg",
    syntaxExample: "!pelotu2",
  },
  {
    id: "corre",
    name: "!corre",
    category: "sonidos",
    tag: "AUDIO PANICO",
    shortDesc: "Alerta de escape en zona azul.",
    whatItDoes: "Suena la música o grito desesperado de '¡Corré, guacho, corré!'.",
    whyItExists: "Ideal cuando los persigue la zona azul a pie sin botiquines ni auto.",
    botResponse: "[Reproduciendo: ¡RUN / CORRÉ!]",
    soundName: "Corré",
    botType: "Sound Alert",
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    priceLabel: "Audio Weezyx",
    purchasePlatform: "weezyx.com/t/pipa_arg",
    syntaxExample: "!corre",
  },
  {
    id: "boca",
    name: "!boca",
    category: "sonidos",
    tag: "AUDIO BOCA JRS",
    shortDesc: "Grito desaforado bostero.",
    whatItDoes: "Reproduce la icónica frase '¡BOCAAA BOCAAA!'.",
    whyItExists: "Varios en el squad (como Mauricabj) son hinchas fanáticos de Boca Juniors.",
    botResponse: "[Reproduciendo: ¡ESTO ES BOCAAA!]",
    soundName: "Boca",
    botType: "Sound Alert",
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    priceLabel: "Audio Weezyx",
    purchasePlatform: "weezyx.com/t/pipa_arg",
    syntaxExample: "!boca",
  },
  {
    id: "acasa",
    name: "!acasa",
    category: "sonidos",
    tag: "AUDIO WIPE",
    shortDesc: "Celebración tras eliminar a una escuadra rival.",
    whatItDoes: "Reproduce el remate '¡A casa, pete, a dormir!'.",
    whyItExists: "El festejo tradicional de PIPAA luego de mandar al lobby a un squad entero.",
    botResponse: "[Reproduciendo: ¡A casaaaaaa!]",
    soundName: "A Casa",
    botType: "Sound Alert",
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    priceLabel: "Audio Weezyx",
    purchasePlatform: "weezyx.com/t/pipa_arg",
    syntaxExample: "!acasa",
  },
  {
    id: "maleta",
    name: "!maleta",
    category: "sonidos",
    tag: "AUDIO MALETA",
    shortDesc: "Para cuando alguien no le pega a nada.",
    whatItDoes: "Emite el audio 'Gordo malooo, maletaaa'.",
    whyItExists: "Típica gastada cuando PIPAA erra con la Mini14 a 50 metros.",
    botResponse: "[Reproduciendo: ¡GORDO MALETAAAA!]",
    soundName: "Maleta",
    botType: "Sound Alert",
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    priceLabel: "Audio Weezyx",
    purchasePlatform: "weezyx.com/t/pipa_arg",
    syntaxExample: "!maleta",
  },
  {
    id: "susto",
    name: "!susto",
    category: "sonidos",
    tag: "JUMPSCARE",
    shortDesc: "Alerta de susto repentino.",
    whatItDoes: "Detona un grito estridente para hacer saltar a PIPAA de la silla.",
    whyItExists: "Los espectadores esperan que esté concentrado apuntando con la mira telescópica para tirárselo.",
    botResponse: "[Reproduciendo: ¡¡¡AHHHHHHH JUMPSCARE!!!]",
    soundName: "Susto",
    botType: "Sound Alert",
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    priceLabel: "Audio Weezyx",
    purchasePlatform: "weezyx.com/t/pipa_arg",
    syntaxExample: "!susto",
  },
  {
    id: "bomberos",
    name: "!bomberos",
    category: "sonidos",
    tag: "SIRENA",
    shortDesc: "Sirena de alarma máxima en la partida.",
    whatItDoes: "Suena una sirena de autobomba.",
    whyItExists: "Utilizado cuando caen 3 squads juntos en Pochinki o Hacienda.",
    botResponse: "[Reproduciendo: Sirena de Bomberos WEE-WOO]",
    soundName: "Bomberos",
    botType: "Sound Alert",
    purchaseUrl: "https://weezyx.com/t/pipa_arg",
    priceLabel: "Audio Weezyx",
    purchasePlatform: "weezyx.com/t/pipa_arg",
    syntaxExample: "!bomberos",
  },
];
